import { useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { AdminPageHeading, AdminShell } from "@/components/admin/admin-shell";
import { createAdminRefundCaseFn, loadAdminRefundCases, updateAdminRefundCaseFn } from "@/lib/api/delivery";

type RefundCase = { id: string; orderId: string; customerId: string; customerEmail: string | null; paymentId: string | null; totalPaise: number; status: string; reason: string; providerReference: string | null; requestedBy: string; createdAt: string; updatedAt: string };
export const Route = createFileRoute("/admin/refunds")({ component: AdminRefundsRoute });
function AdminRefundsRoute() {
  const [cases, setCases] = useState<RefundCase[]>([]);
  const [orderId, setOrderId] = useState("");
  const [reason, setReason] = useState("");
  const [providerReferences, setProviderReferences] = useState<Record<string, string>>({});
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState("");
  async function refresh() { const result = await loadAdminRefundCases(); if (result.success) setCases(result.refundCases); else setError(result.message); }
  useEffect(() => { void refresh().catch(() => setError("Could not load refund cases.")); }, []);
  async function create(event: React.FormEvent) { event.preventDefault(); setBusy("new"); setError(""); setMessage(""); try { const result = await createAdminRefundCaseFn({ data: { orderId: orderId.trim(), reason: reason.trim() } }); if (!result.success) setError(result.message); else { setOrderId(""); setReason(""); setMessage("Refund case opened for review; no refund has been issued."); await refresh(); } } catch { setError("Could not create refund case."); } finally { setBusy(""); } }
  async function update(refundCase: RefundCase, status: "UNDER_REVIEW" | "APPROVED" | "DECLINED" | "EXTERNAL_REFUND_RECORDED") { setBusy(refundCase.id); setError(""); setMessage(""); const providerReference = providerReferences[refundCase.id]?.trim(); try { const result = await updateAdminRefundCaseFn({ data: { caseId: refundCase.id, status, ...(status === "EXTERNAL_REFUND_RECORDED" ? { providerReference } : {}) } }); if (!result.success) setError(result.message); else { setMessage(status === "EXTERNAL_REFUND_RECORDED" ? "External refund reference recorded." : `Refund case moved to ${status}.`); await refresh(); } } catch { setError("Could not update refund case."); } finally { setBusy(""); } }
  return <AdminShell><AdminPageHeading title="Refund review" description="This workspace tracks and approves refund requests but never moves money. An external refund must be issued via the provider console and its reference recorded here." />{error && <p role="alert" className="mb-4 text-sm text-danger">{error}</p>}{message && <p role="status" className="mb-4 text-sm text-success">{message}</p>}<form className="card-surface mb-6 grid gap-3 p-5 sm:grid-cols-[1fr_2fr_auto] sm:items-end" onSubmit={(event) => void create(event)}><label className="text-sm font-medium">Paid order ID<input required className="field mt-1 w-full" value={orderId} onChange={(event) => setOrderId(event.target.value)} /></label><label className="text-sm font-medium">Reason<textarea required minLength={5} maxLength={500} className="field mt-1 w-full" value={reason} onChange={(event) => setReason(event.target.value)} /></label><button className="btn-primary" disabled={Boolean(busy)}>Open case</button></form><section className="card-surface divide-y divide-line">{cases.map((item) => <article key={item.id} className="grid gap-4 p-5"><div className="flex flex-wrap justify-between gap-2"><div><h2 className="font-bold">Order {item.orderId} · {item.status}</h2><p className="text-xs text-muted">{item.customerEmail ?? item.customerId} · payment {item.paymentId ?? "unknown"} · {item.totalPaise} paise</p></div><p className="text-xs text-muted">Case {item.id}</p></div><p className="text-sm">{item.reason}</p>{item.providerReference && <p className="text-xs text-muted">Provider reference: {item.providerReference}</p>}<div className="flex flex-wrap gap-2">{item.status === "OPEN" && <button className="btn-outline" disabled={Boolean(busy)} onClick={() => void update(item, "UNDER_REVIEW")}>Start review</button>}{item.status === "UNDER_REVIEW" && <><button className="btn-outline" disabled={Boolean(busy)} onClick={() => void update(item, "APPROVED")}>Approve request</button><button className="btn-outline" disabled={Boolean(busy)} onClick={() => void update(item, "DECLINED")}>Decline</button></>}{item.status === "APPROVED" && <><input className="field min-h-9" placeholder="External refund reference" value={providerReferences[item.id] ?? ""} onChange={(event) => setProviderReferences((current) => ({ ...current, [item.id]: event.target.value }))} /><button className="btn-outline" disabled={Boolean(busy) || !providerReferences[item.id]?.trim()} onClick={() => void update(item, "EXTERNAL_REFUND_RECORDED")}>Record external refund</button></>}</div></article>)}{cases.length === 0 && <p className="p-8 text-sm text-muted">No refund cases.</p>}</section></AdminShell>;
}
