import { useEffect, useState } from "react";
import { Link, createFileRoute } from "@tanstack/react-router";
import { DeliveryPageHeading, DeliveryShell } from "@/components/delivery/delivery-shell";
import { loadAssignedDeliveryOrder, loadMyDeliveryAssignments, updateAssignedDeliveryStatus } from "@/lib/api/delivery";
import type { DeliveryAssignment } from "@/lib/server/delivery";
import type { OrderRecord } from "@/lib/server/orders";

export const Route = createFileRoute("/delivery/orders")({ component: DeliveryOrdersRoute });
function DeliveryOrdersRoute() {
  const [assignments, setAssignments] = useState<DeliveryAssignment[]>([]);
  const [selected, setSelected] = useState<{ assignment: DeliveryAssignment; order: OrderRecord } | null>(null);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  async function refresh() { const result = await loadMyDeliveryAssignments(); if (result.success) setAssignments(result.assignments); else setError(result.message); }
  useEffect(() => { void refresh().catch(() => setError("Could not load assigned deliveries.")); }, []);
  async function open(orderId: string) { setSelected(null); setError(""); try { const result = await loadAssignedDeliveryOrder({ data: { orderId } }); if (result.success) setSelected(result); else setError(result.message); } catch { setError("Could not load this assigned order."); } }
  async function move(status: "PICKED_UP" | "DELIVERED") { if (!selected) return; setBusy(true); setError(""); try { const result = await updateAssignedDeliveryStatus({ data: { orderId: selected.order.id, status } }); if (!result.success) setError(result.message); else { setSelected(null); await refresh(); } } catch { setError("Could not update delivery status."); } finally { setBusy(false); } }
  return <DeliveryShell><DeliveryPageHeading title="Assigned orders" description="Only orders assigned to your authenticated partner account are listed and available for pickup or completion." />{error && <p role="alert" className="mb-4 text-sm text-danger">{error}</p>}<section className="card-surface divide-y divide-line">{assignments.map((assignment) => <article key={assignment.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-semibold">Order {assignment.orderId}</p><p className="text-xs text-muted">{assignment.status.replaceAll("_", " ")} · assigned {new Date(assignment.assignedAt).toLocaleString()}</p></div><button className="btn-outline min-h-9" onClick={() => void open(assignment.orderId)}>View order</button></article>)}{assignments.length === 0 && <p className="p-8 text-sm text-muted">No active deliveries are assigned to you. Visit <Link to="/delivery/settings" className="font-semibold text-primary">Settings</Link> to confirm your availability.</p>}</section>{selected && <section className="card-surface mt-5 p-5"><h2 className="text-lg font-bold">Order {selected.order.id}</h2><p className="mt-1 text-sm text-muted">Payment {selected.order.paymentStatus} · {selected.order.orderStatus.replaceAll("_", " ")}</p><div className="mt-4 divide-y divide-line">{selected.order.items.map((item) => <div key={item.productId} className="flex justify-between gap-4 py-2 text-sm"><span>{item.productName} × {item.quantity}</span><span>{item.subtotalPaise} paise</span></div>)}</div><p className="mt-4 text-sm">Deliver to: {selected.order.customer.firstName} {selected.order.customer.lastName}, {selected.order.customer.addressLine}, {selected.order.customer.city} {selected.order.customer.pincode}</p><div className="mt-5 flex gap-2">{selected.assignment.status === "ASSIGNED" && <button className="btn-primary" disabled={busy} onClick={() => void move("PICKED_UP")}>Confirm pickup</button>}{selected.assignment.status === "PICKED_UP" && <button className="btn-primary" disabled={busy} onClick={() => void move("DELIVERED")}>Complete delivery</button>}<button className="btn-outline" onClick={() => setSelected(null)}>Close</button></div></section>}</DeliveryShell>;
}
