import { useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { ShieldCheck } from "lucide-react";
import { VendorNotice, VendorPageHeading, VendorShell } from "@/components/vendor/vendor-shell";
import { loadVendorDashboardFn } from "@/lib/api/vendor";
export const Route = createFileRoute("/vendor/subscription")({ component: SubscriptionRoute });
function SubscriptionRoute() { const [subscription, setSubscription] = useState<{ plan_name: string; price_paise: number; billing_cycle: string; status: string; starts_at: string | null; next_due_at: string | null; expires_at: string | null; payment_method: string | null } | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); useEffect(() => { void loadVendorDashboardFn().then((r) => { if (r.success) setSubscription(r.dashboard.subscription); else setError(r.message); setLoading(false); }); }, []); const days = subscription?.expires_at ? Math.ceil((new Date(subscription.expires_at).getTime() - Date.now()) / 86400000) : null; return <VendorShell><VendorPageHeading eyebrow="Vendor subscription" title="Subscription overview" description="An active subscription is required for new listings and inventory increases." />{error && <VendorNotice tone="warning">{error}</VendorNotice>}{loading ? <p className="py-10 text-sm text-muted">Loading subscription…</p> : <div className="grid gap-5 lg:grid-cols-[1fr_20rem]"><section className="card-surface p-6"><div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-full bg-blue-50 text-primary"><ShieldCheck className="size-6" /></span><div><p className="text-sm text-muted">Current plan</p><h2 className="text-2xl font-extrabold">{subscription?.plan_name ?? "No active plan"}</h2></div></div>{subscription ? <><p className="mt-5 text-3xl font-extrabold">₹{(subscription.price_paise / 100).toLocaleString("en-IN")}<span className="text-sm font-medium text-muted"> / {subscription.billing_cycle.toLowerCase()}</span></p><div className="mt-5 grid gap-3 border-t border-line pt-5 text-sm sm:grid-cols-2"><Info label="Status" value={subscription.status} /><Info label="Payment method" value={subscription.payment_method ?? "Not configured"} /><Info label="Started" value={formatDate(subscription.starts_at)} /><Info label="Next due" value={formatDate(subscription.next_due_at)} /><Info label="Expires" value={formatDate(subscription.expires_at)} /><Info label="Remaining" value={days == null ? "—" : `${Math.max(0, days)} day(s)`} /></div>{days != null && days <= 7 && <div className="mt-5"><VendorNotice tone="warning">Your plan is expiring soon. Renewal payments are not connected yet.</VendorNotice></div>}</> : <p className="mt-4 text-sm text-muted">Vendor approval creates a 30-day starter trial.</p>}</section><aside className="card-surface h-fit p-5"><h2 className="font-bold">Plans & billing</h2><p className="mt-2 text-sm text-muted">Paid plan checkout is not configured, so renewal and upgrade actions are unavailable.</p><button type="button" disabled className="btn-primary mt-4 w-full opacity-60">Renew subscription</button></aside></div>}</VendorShell>; }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted">{label}</p><p className="mt-0.5 font-semibold">{value}</p></div>; }
function formatDate(value: string | null) { return value ? new Date(value).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" }) : "—"; }
