import { useEffect, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { VendorNotice, VendorPageHeading, VendorShell } from "@/components/vendor/vendor-shell";
import { addVendorProductFn } from "@/lib/api/vendor";
import { fetchProducts } from "@/lib/api/public";
import type { ProductRow } from "@/lib/server/catalog";
export const Route = createFileRoute("/vendor/inventory/add")({ component: AddInventoryRoute });
function AddInventoryRoute() {
  const [catalog, setCatalog] = useState<ProductRow[]>([]); const [productId, setProductId] = useState(""); const [price, setPrice] = useState(""); const [quantity, setQuantity] = useState("0"); const [minimumStock, setMinimumStock] = useState("5"); const [error, setError] = useState(""); const [success, setSuccess] = useState(false); const [busy, setBusy] = useState(false);
  useEffect(() => { void fetchProducts({ data: {} }).then((r) => { if (r.success) setCatalog(r.products); }); }, []);
  const selected = catalog.find((p) => p.id === productId);
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); const result = await addVendorProductFn({ data: { productId, sellingPricePaise: Math.round(Number(price) * 100), quantity: Number(quantity), minimumStock: Number(minimumStock) } }); setBusy(false); if (result.success) setSuccess(true); else setError(result.message); }
  return <VendorShell><VendorPageHeading eyebrow="Inventory · Add product" title="Add product to shop" description="Choose from the PrintHub global catalog; vendors cannot create or change global products." />{success ? <section className="card-surface max-w-2xl p-6"><h2 className="text-lg font-bold">Product added to your shop</h2><p className="mt-2 text-sm text-muted">This listing has its own vendor price and available stock.</p><Link to="/vendor/inventory" className="btn-primary mt-5">View inventory</Link></section> : <form onSubmit={(e) => void submit(e)} className="card-surface grid max-w-3xl gap-5 p-5 sm:p-7"><label className="block text-sm font-semibold">Select global product<select className="field mt-1 w-full" value={productId} onChange={(e) => { const id = e.target.value; setProductId(id); const found = catalog.find((p) => p.id === id); if (found) setPrice((found.price_paise / 100).toFixed(2)); }} required><option value="">Choose a PrintHub product…</option>{catalog.map((p) => <option key={p.id} value={p.id}>{p.name} · {p.category}</option>)}</select></label>{selected && <div className="flex items-center gap-4 rounded-xl bg-canvas p-4"><img src={selected.image} alt="" className="size-16 rounded-lg object-cover" /><div><p className="font-bold">{selected.name}</p><p className="text-sm text-muted">{selected.description}</p><p className="mt-1 text-xs text-muted">Global category: {selected.category}</p></div></div>}<div className="grid gap-4 sm:grid-cols-3"><Field label="Selling price (₹)" value={price} onChange={setPrice} min="0" step="0.01" /><Field label="Available quantity" value={quantity} onChange={setQuantity} min="0" step="1" /><Field label="Minimum stock alert" value={minimumStock} onChange={setMinimumStock} min="0" step="1" /></div><VendorNotice>Only the shop's selling price and inventory are created here. The global catalog product remains unchanged.</VendorNotice>{error && <p role="alert" className="text-sm text-danger">{error}</p>}<div className="flex flex-wrap gap-3"><button className="btn-primary" disabled={busy || catalog.length === 0}>{busy ? "Adding…" : "Add product"}</button><Link to="/vendor/inventory" className="btn-outline">Cancel</Link></div></form>}</VendorShell>;
}
function Field({ label, value, onChange, min, step }: { label: string; value: string; onChange: (v: string) => void; min: string; step: string }) { return <label className="block text-sm font-semibold">{label}<span className="field mt-1"><input type="number" value={value} min={min} step={step} onChange={(e) => onChange(e.target.value)} required /></span></label>; }
