/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminDeliveryPartnersRouteImport } from './routes/admin.delivery-partners'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminRefundsRouteImport } from './routes/admin.refunds'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminShopsRouteImport } from './routes/admin.shops'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as DeliveryAdminRouteImport } from './routes/delivery.admin'
import { Route as DeliveryDashboardRouteImport } from './routes/delivery.dashboard'
import { Route as DeliveryEarningsRouteImport } from './routes/delivery.earnings'
import { Route as DeliveryHistoryRouteImport } from './routes/delivery.history'
import { Route as DeliveryNotificationsRouteImport } from './routes/delivery.notifications'
import { Route as DeliveryOrdersRouteImport } from './routes/delivery.orders'
import { Route as DeliveryProfileRouteImport } from './routes/delivery.profile'
import { Route as DeliveryRequestRouteImport } from './routes/delivery.request'
import { Route as DeliverySettingsRouteImport } from './routes/delivery.settings'
import { Route as InvoiceOrderIdRouteImport } from './routes/invoice.$orderId'
import { Route as OrderSuccessOrderIdRouteImport } from './routes/order-success.$orderId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as VendorAdminRouteImport } from './routes/vendor.admin'
import { Route as VendorApplicationRouteImport } from './routes/vendor.application'
import { Route as VendorCustomersRouteImport } from './routes/vendor.customers'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard'
import { Route as VendorNotificationsRouteImport } from './routes/vendor.notifications'
import { Route as VendorOrdersRouteImport } from './routes/vendor.orders'
import { Route as VendorPaymentDetailsRouteImport } from './routes/vendor.payment-details'
import { Route as VendorPickupRouteImport } from './routes/vendor.pickup'
import { Route as VendorProfileRouteImport } from './routes/vendor.profile'
import { Route as VendorReceiptsRouteImport } from './routes/vendor.receipts'
import { Route as VendorSalesRouteImport } from './routes/vendor.sales'
import { Route as VendorSettingsRouteImport } from './routes/vendor.settings'
import { Route as VendorShopRouteImport } from './routes/vendor.shop'
import { Route as VendorSubscriptionRouteImport } from './routes/vendor.subscription'
import { Route as VendorSupportRouteImport } from './routes/vendor.support'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAuthConfigRouteImport } from './routes/api/auth.config'
import { Route as ApiPaymentsWebhookRouteImport } from './routes/api/payments.webhook'
import { Route as VendorInventoryIndexRouteImport } from './routes/vendor.inventory.index'
import { Route as VendorInventoryAddRouteImport } from './routes/vendor.inventory.add'
import { Route as VendorInventoryHistoryRouteImport } from './routes/vendor.inventory.history'
import { Route as VendorInventoryLowStockRouteImport } from './routes/vendor.inventory.low-stock'
import { Route as VendorInventoryStockRouteImport } from './routes/vendor.inventory.stock'
import { Route as VendorReceiptsSubscriptionsRouteImport } from './routes/vendor.receipts.subscriptions'
import { Route as VendorSubscriptionPaymentHistoryRouteImport } from './routes/vendor.subscription.payment-history'
import { Route as VendorSubscriptionPlansRouteImport } from './routes/vendor.subscription.plans'
import { Route as ApiInvoicesOrderIdPdfRouteImport } from './routes/api/invoices.$orderId.pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDeliveryPartnersRoute = AdminDeliveryPartnersRouteImport.update({
  id: '/admin/delivery-partners',
  path: '/admin/delivery-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/admin/refunds',
  path: '/admin/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShopsRoute = AdminShopsRouteImport.update({
  id: '/admin/shops',
  path: '/admin/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/admin/vendors',
  path: '/admin/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryAdminRoute = DeliveryAdminRouteImport.update({
  id: '/delivery/admin',
  path: '/delivery/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryDashboardRoute = DeliveryDashboardRouteImport.update({
  id: '/delivery/dashboard',
  path: '/delivery/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryEarningsRoute = DeliveryEarningsRouteImport.update({
  id: '/delivery/earnings',
  path: '/delivery/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryHistoryRoute = DeliveryHistoryRouteImport.update({
  id: '/delivery/history',
  path: '/delivery/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryNotificationsRoute = DeliveryNotificationsRouteImport.update({
  id: '/delivery/notifications',
  path: '/delivery/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryOrdersRoute = DeliveryOrdersRouteImport.update({
  id: '/delivery/orders',
  path: '/delivery/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryProfileRoute = DeliveryProfileRouteImport.update({
  id: '/delivery/profile',
  path: '/delivery/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRequestRoute = DeliveryRequestRouteImport.update({
  id: '/delivery/request',
  path: '/delivery/request',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliverySettingsRoute = DeliverySettingsRouteImport.update({
  id: '/delivery/settings',
  path: '/delivery/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceOrderIdRoute = InvoiceOrderIdRouteImport.update({
  id: '/invoice/$orderId',
  path: '/invoice/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessOrderIdRoute = OrderSuccessOrderIdRouteImport.update({
  id: '/order-success/$orderId',
  path: '/order-success/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRoute,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const VendorAdminRoute = VendorAdminRouteImport.update({
  id: '/vendor/admin',
  path: '/vendor/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorApplicationRoute = VendorApplicationRouteImport.update({
  id: '/vendor/application',
  path: '/vendor/application',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorCustomersRoute = VendorCustomersRouteImport.update({
  id: '/vendor/customers',
  path: '/vendor/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorNotificationsRoute = VendorNotificationsRouteImport.update({
  id: '/vendor/notifications',
  path: '/vendor/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/vendor/orders',
  path: '/vendor/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorPaymentDetailsRoute = VendorPaymentDetailsRouteImport.update({
  id: '/vendor/payment-details',
  path: '/vendor/payment-details',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorPickupRoute = VendorPickupRouteImport.update({
  id: '/vendor/pickup',
  path: '/vendor/pickup',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorProfileRoute = VendorProfileRouteImport.update({
  id: '/vendor/profile',
  path: '/vendor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorReceiptsRoute = VendorReceiptsRouteImport.update({
  id: '/vendor/receipts',
  path: '/vendor/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorSalesRoute = VendorSalesRouteImport.update({
  id: '/vendor/sales',
  path: '/vendor/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorSettingsRoute = VendorSettingsRouteImport.update({
  id: '/vendor/settings',
  path: '/vendor/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorShopRoute = VendorShopRouteImport.update({
  id: '/vendor/shop',
  path: '/vendor/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorSubscriptionRoute = VendorSubscriptionRouteImport.update({
  id: '/vendor/subscription',
  path: '/vendor/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorSupportRoute = VendorSupportRouteImport.update({
  id: '/vendor/support',
  path: '/vendor/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthConfigRoute = ApiAuthConfigRouteImport.update({
  id: '/api/auth/config',
  path: '/api/auth/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsWebhookRoute = ApiPaymentsWebhookRouteImport.update({
  id: '/api/payments/webhook',
  path: '/api/payments/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorInventoryIndexRoute = VendorInventoryIndexRouteImport.update({
  id: '/vendor/inventory/',
  path: '/vendor/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorInventoryAddRoute = VendorInventoryAddRouteImport.update({
  id: '/vendor/inventory/add',
  path: '/vendor/inventory/add',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorInventoryHistoryRoute = VendorInventoryHistoryRouteImport.update({
  id: '/vendor/inventory/history',
  path: '/vendor/inventory/history',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorInventoryLowStockRoute = VendorInventoryLowStockRouteImport.update({
  id: '/vendor/inventory/low-stock',
  path: '/vendor/inventory/low-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorInventoryStockRoute = VendorInventoryStockRouteImport.update({
  id: '/vendor/inventory/stock',
  path: '/vendor/inventory/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorReceiptsSubscriptionsRoute =
  VendorReceiptsSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => VendorReceiptsRoute,
  } as any)
const VendorSubscriptionPaymentHistoryRoute =
  VendorSubscriptionPaymentHistoryRouteImport.update({
    id: '/payment-history',
    path: '/payment-history',
    getParentRoute: () => VendorSubscriptionRoute,
  } as any)
const VendorSubscriptionPlansRoute = VendorSubscriptionPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => VendorSubscriptionRoute,
} as any)
const ApiInvoicesOrderIdPdfRoute = ApiInvoicesOrderIdPdfRouteImport.update({
  id: '/api/invoices/$orderId/pdf',
  path: '/api/invoices/$orderId/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/delivery-partners': typeof AdminDeliveryPartnersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/delivery/admin': typeof DeliveryAdminRoute
  '/delivery/dashboard': typeof DeliveryDashboardRoute
  '/delivery/earnings': typeof DeliveryEarningsRoute
  '/delivery/history': typeof DeliveryHistoryRoute
  '/delivery/notifications': typeof DeliveryNotificationsRoute
  '/delivery/orders': typeof DeliveryOrdersRoute
  '/delivery/profile': typeof DeliveryProfileRoute
  '/delivery/request': typeof DeliveryRequestRoute
  '/delivery/settings': typeof DeliverySettingsRoute
  '/invoice/$orderId': typeof InvoiceOrderIdRoute
  '/order-success/$orderId': typeof OrderSuccessOrderIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/vendor/admin': typeof VendorAdminRoute
  '/vendor/application': typeof VendorApplicationRoute
  '/vendor/customers': typeof VendorCustomersRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/payment-details': typeof VendorPaymentDetailsRoute
  '/vendor/pickup': typeof VendorPickupRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/receipts': typeof VendorReceiptsRouteWithChildren
  '/vendor/sales': typeof VendorSalesRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/vendor/shop': typeof VendorShopRoute
  '/vendor/subscription': typeof VendorSubscriptionRouteWithChildren
  '/vendor/support': typeof VendorSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/config': typeof ApiAuthConfigRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/vendor/inventory/add': typeof VendorInventoryAddRoute
  '/vendor/inventory/history': typeof VendorInventoryHistoryRoute
  '/vendor/inventory/low-stock': typeof VendorInventoryLowStockRoute
  '/vendor/inventory/stock': typeof VendorInventoryStockRoute
  '/vendor/receipts/subscriptions': typeof VendorReceiptsSubscriptionsRoute
  '/vendor/subscription/payment-history': typeof VendorSubscriptionPaymentHistoryRoute
  '/vendor/subscription/plans': typeof VendorSubscriptionPlansRoute
  '/vendor/inventory/': typeof VendorInventoryIndexRoute
  '/api/invoices/$orderId/pdf': typeof ApiInvoicesOrderIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/delivery-partners': typeof AdminDeliveryPartnersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/delivery/admin': typeof DeliveryAdminRoute
  '/delivery/dashboard': typeof DeliveryDashboardRoute
  '/delivery/earnings': typeof DeliveryEarningsRoute
  '/delivery/history': typeof DeliveryHistoryRoute
  '/delivery/notifications': typeof DeliveryNotificationsRoute
  '/delivery/orders': typeof DeliveryOrdersRoute
  '/delivery/profile': typeof DeliveryProfileRoute
  '/delivery/request': typeof DeliveryRequestRoute
  '/delivery/settings': typeof DeliverySettingsRoute
  '/invoice/$orderId': typeof InvoiceOrderIdRoute
  '/order-success/$orderId': typeof OrderSuccessOrderIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/vendor/admin': typeof VendorAdminRoute
  '/vendor/application': typeof VendorApplicationRoute
  '/vendor/customers': typeof VendorCustomersRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/payment-details': typeof VendorPaymentDetailsRoute
  '/vendor/pickup': typeof VendorPickupRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/receipts': typeof VendorReceiptsRouteWithChildren
  '/vendor/sales': typeof VendorSalesRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/vendor/shop': typeof VendorShopRoute
  '/vendor/subscription': typeof VendorSubscriptionRouteWithChildren
  '/vendor/support': typeof VendorSupportRoute
  '/admin': typeof AdminIndexRoute
  '/products': typeof ProductsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/config': typeof ApiAuthConfigRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/vendor/inventory/add': typeof VendorInventoryAddRoute
  '/vendor/inventory/history': typeof VendorInventoryHistoryRoute
  '/vendor/inventory/low-stock': typeof VendorInventoryLowStockRoute
  '/vendor/inventory/stock': typeof VendorInventoryStockRoute
  '/vendor/receipts/subscriptions': typeof VendorReceiptsSubscriptionsRoute
  '/vendor/subscription/payment-history': typeof VendorSubscriptionPaymentHistoryRoute
  '/vendor/subscription/plans': typeof VendorSubscriptionPlansRoute
  '/vendor/inventory': typeof VendorInventoryIndexRoute
  '/api/invoices/$orderId/pdf': typeof ApiInvoicesOrderIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/delivery-partners': typeof AdminDeliveryPartnersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/delivery/admin': typeof DeliveryAdminRoute
  '/delivery/dashboard': typeof DeliveryDashboardRoute
  '/delivery/earnings': typeof DeliveryEarningsRoute
  '/delivery/history': typeof DeliveryHistoryRoute
  '/delivery/notifications': typeof DeliveryNotificationsRoute
  '/delivery/orders': typeof DeliveryOrdersRoute
  '/delivery/profile': typeof DeliveryProfileRoute
  '/delivery/request': typeof DeliveryRequestRoute
  '/delivery/settings': typeof DeliverySettingsRoute
  '/invoice/$orderId': typeof InvoiceOrderIdRoute
  '/order-success/$orderId': typeof OrderSuccessOrderIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/vendor/admin': typeof VendorAdminRoute
  '/vendor/application': typeof VendorApplicationRoute
  '/vendor/customers': typeof VendorCustomersRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/notifications': typeof VendorNotificationsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/payment-details': typeof VendorPaymentDetailsRoute
  '/vendor/pickup': typeof VendorPickupRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/receipts': typeof VendorReceiptsRouteWithChildren
  '/vendor/sales': typeof VendorSalesRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/vendor/shop': typeof VendorShopRoute
  '/vendor/subscription': typeof VendorSubscriptionRouteWithChildren
  '/vendor/support': typeof VendorSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/config': typeof ApiAuthConfigRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/vendor/inventory/add': typeof VendorInventoryAddRoute
  '/vendor/inventory/history': typeof VendorInventoryHistoryRoute
  '/vendor/inventory/low-stock': typeof VendorInventoryLowStockRoute
  '/vendor/inventory/stock': typeof VendorInventoryStockRoute
  '/vendor/receipts/subscriptions': typeof VendorReceiptsSubscriptionsRoute
  '/vendor/subscription/payment-history': typeof VendorSubscriptionPaymentHistoryRoute
  '/vendor/subscription/plans': typeof VendorSubscriptionPlansRoute
  '/vendor/inventory/': typeof VendorInventoryIndexRoute
  '/api/invoices/$orderId/pdf': typeof ApiInvoicesOrderIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/orders'
    | '/privacy'
    | '/products'
    | '/profile'
    | '/register'
    | '/services'
    | '/terms'
    | '/admin/audit'
    | '/admin/delivery-partners'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/refunds'
    | '/admin/services'
    | '/admin/shops'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/admin/vendors'
    | '/delivery/admin'
    | '/delivery/dashboard'
    | '/delivery/earnings'
    | '/delivery/history'
    | '/delivery/notifications'
    | '/delivery/orders'
    | '/delivery/profile'
    | '/delivery/request'
    | '/delivery/settings'
    | '/invoice/$orderId'
    | '/order-success/$orderId'
    | '/orders/$orderId'
    | '/products/$id'
    | '/reset-password/$token'
    | '/services/$slug'
    | '/vendor/admin'
    | '/vendor/application'
    | '/vendor/customers'
    | '/vendor/dashboard'
    | '/vendor/notifications'
    | '/vendor/orders'
    | '/vendor/payment-details'
    | '/vendor/pickup'
    | '/vendor/profile'
    | '/vendor/receipts'
    | '/vendor/sales'
    | '/vendor/settings'
    | '/vendor/shop'
    | '/vendor/subscription'
    | '/vendor/support'
    | '/admin/'
    | '/products/'
    | '/services/'
    | '/api/auth/$'
    | '/api/auth/config'
    | '/api/payments/webhook'
    | '/vendor/inventory/add'
    | '/vendor/inventory/history'
    | '/vendor/inventory/low-stock'
    | '/vendor/inventory/stock'
    | '/vendor/receipts/subscriptions'
    | '/vendor/subscription/payment-history'
    | '/vendor/subscription/plans'
    | '/vendor/inventory/'
    | '/api/invoices/$orderId/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/orders'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/terms'
    | '/admin/audit'
    | '/admin/delivery-partners'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/refunds'
    | '/admin/services'
    | '/admin/shops'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/admin/vendors'
    | '/delivery/admin'
    | '/delivery/dashboard'
    | '/delivery/earnings'
    | '/delivery/history'
    | '/delivery/notifications'
    | '/delivery/orders'
    | '/delivery/profile'
    | '/delivery/request'
    | '/delivery/settings'
    | '/invoice/$orderId'
    | '/order-success/$orderId'
    | '/orders/$orderId'
    | '/products/$id'
    | '/reset-password/$token'
    | '/services/$slug'
    | '/vendor/admin'
    | '/vendor/application'
    | '/vendor/customers'
    | '/vendor/dashboard'
    | '/vendor/notifications'
    | '/vendor/orders'
    | '/vendor/payment-details'
    | '/vendor/pickup'
    | '/vendor/profile'
    | '/vendor/receipts'
    | '/vendor/sales'
    | '/vendor/settings'
    | '/vendor/shop'
    | '/vendor/subscription'
    | '/vendor/support'
    | '/admin'
    | '/products'
    | '/services'
    | '/api/auth/$'
    | '/api/auth/config'
    | '/api/payments/webhook'
    | '/vendor/inventory/add'
    | '/vendor/inventory/history'
    | '/vendor/inventory/low-stock'
    | '/vendor/inventory/stock'
    | '/vendor/receipts/subscriptions'
    | '/vendor/subscription/payment-history'
    | '/vendor/subscription/plans'
    | '/vendor/inventory'
    | '/api/invoices/$orderId/pdf'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/orders'
    | '/privacy'
    | '/products'
    | '/profile'
    | '/register'
    | '/services'
    | '/terms'
    | '/admin/audit'
    | '/admin/delivery-partners'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/refunds'
    | '/admin/services'
    | '/admin/shops'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/admin/vendors'
    | '/delivery/admin'
    | '/delivery/dashboard'
    | '/delivery/earnings'
    | '/delivery/history'
    | '/delivery/notifications'
    | '/delivery/orders'
    | '/delivery/profile'
    | '/delivery/request'
    | '/delivery/settings'
    | '/invoice/$orderId'
    | '/order-success/$orderId'
    | '/orders/$orderId'
    | '/products/$id'
    | '/reset-password/$token'
    | '/services/$slug'
    | '/vendor/admin'
    | '/vendor/application'
    | '/vendor/customers'
    | '/vendor/dashboard'
    | '/vendor/notifications'
    | '/vendor/orders'
    | '/vendor/payment-details'
    | '/vendor/pickup'
    | '/vendor/profile'
    | '/vendor/receipts'
    | '/vendor/sales'
    | '/vendor/settings'
    | '/vendor/shop'
    | '/vendor/subscription'
    | '/vendor/support'
    | '/admin/'
    | '/products/'
    | '/services/'
    | '/api/auth/$'
    | '/api/auth/config'
    | '/api/payments/webhook'
    | '/vendor/inventory/add'
    | '/vendor/inventory/history'
    | '/vendor/inventory/low-stock'
    | '/vendor/inventory/stock'
    | '/vendor/receipts/subscriptions'
    | '/vendor/subscription/payment-history'
    | '/vendor/subscription/plans'
    | '/vendor/inventory/'
    | '/api/invoices/$orderId/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDeliveryPartnersRoute: typeof AdminDeliveryPartnersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRefundsRoute: typeof AdminRefundsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminShopsRoute: typeof AdminShopsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  DeliveryAdminRoute: typeof DeliveryAdminRoute
  DeliveryDashboardRoute: typeof DeliveryDashboardRoute
  DeliveryEarningsRoute: typeof DeliveryEarningsRoute
  DeliveryHistoryRoute: typeof DeliveryHistoryRoute
  DeliveryNotificationsRoute: typeof DeliveryNotificationsRoute
  DeliveryOrdersRoute: typeof DeliveryOrdersRoute
  DeliveryProfileRoute: typeof DeliveryProfileRoute
  DeliveryRequestRoute: typeof DeliveryRequestRoute
  DeliverySettingsRoute: typeof DeliverySettingsRoute
  InvoiceOrderIdRoute: typeof InvoiceOrderIdRoute
  OrderSuccessOrderIdRoute: typeof OrderSuccessOrderIdRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  VendorAdminRoute: typeof VendorAdminRoute
  VendorApplicationRoute: typeof VendorApplicationRoute
  VendorCustomersRoute: typeof VendorCustomersRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorNotificationsRoute: typeof VendorNotificationsRoute
  VendorOrdersRoute: typeof VendorOrdersRoute
  VendorPaymentDetailsRoute: typeof VendorPaymentDetailsRoute
  VendorPickupRoute: typeof VendorPickupRoute
  VendorProfileRoute: typeof VendorProfileRoute
  VendorReceiptsRoute: typeof VendorReceiptsRouteWithChildren
  VendorSalesRoute: typeof VendorSalesRoute
  VendorSettingsRoute: typeof VendorSettingsRoute
  VendorShopRoute: typeof VendorShopRoute
  VendorSubscriptionRoute: typeof VendorSubscriptionRouteWithChildren
  VendorSupportRoute: typeof VendorSupportRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthConfigRoute: typeof ApiAuthConfigRoute
  ApiPaymentsWebhookRoute: typeof ApiPaymentsWebhookRoute
  VendorInventoryAddRoute: typeof VendorInventoryAddRoute
  VendorInventoryHistoryRoute: typeof VendorInventoryHistoryRoute
  VendorInventoryLowStockRoute: typeof VendorInventoryLowStockRoute
  VendorInventoryStockRoute: typeof VendorInventoryStockRoute
  VendorInventoryIndexRoute: typeof VendorInventoryIndexRoute
  ApiInvoicesOrderIdPdfRoute: typeof ApiInvoicesOrderIdPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/delivery-partners': {
      id: '/admin/delivery-partners'
      path: '/admin/delivery-partners'
      fullPath: '/admin/delivery-partners'
      preLoaderRoute: typeof AdminDeliveryPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/admin/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shops': {
      id: '/admin/shops'
      path: '/admin/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AdminShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/admin/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/admin': {
      id: '/delivery/admin'
      path: '/delivery/admin'
      fullPath: '/delivery/admin'
      preLoaderRoute: typeof DeliveryAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/dashboard': {
      id: '/delivery/dashboard'
      path: '/delivery/dashboard'
      fullPath: '/delivery/dashboard'
      preLoaderRoute: typeof DeliveryDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/earnings': {
      id: '/delivery/earnings'
      path: '/delivery/earnings'
      fullPath: '/delivery/earnings'
      preLoaderRoute: typeof DeliveryEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/history': {
      id: '/delivery/history'
      path: '/delivery/history'
      fullPath: '/delivery/history'
      preLoaderRoute: typeof DeliveryHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/notifications': {
      id: '/delivery/notifications'
      path: '/delivery/notifications'
      fullPath: '/delivery/notifications'
      preLoaderRoute: typeof DeliveryNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/orders': {
      id: '/delivery/orders'
      path: '/delivery/orders'
      fullPath: '/delivery/orders'
      preLoaderRoute: typeof DeliveryOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/profile': {
      id: '/delivery/profile'
      path: '/delivery/profile'
      fullPath: '/delivery/profile'
      preLoaderRoute: typeof DeliveryProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/request': {
      id: '/delivery/request'
      path: '/delivery/request'
      fullPath: '/delivery/request'
      preLoaderRoute: typeof DeliveryRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/settings': {
      id: '/delivery/settings'
      path: '/delivery/settings'
      fullPath: '/delivery/settings'
      preLoaderRoute: typeof DeliverySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$orderId': {
      id: '/invoice/$orderId'
      path: '/invoice/$orderId'
      fullPath: '/invoice/$orderId'
      preLoaderRoute: typeof InvoiceOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success/$orderId': {
      id: '/order-success/$orderId'
      path: '/order-success/$orderId'
      fullPath: '/order-success/$orderId'
      preLoaderRoute: typeof OrderSuccessOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/vendor/admin': {
      id: '/vendor/admin'
      path: '/vendor/admin'
      fullPath: '/vendor/admin'
      preLoaderRoute: typeof VendorAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/application': {
      id: '/vendor/application'
      path: '/vendor/application'
      fullPath: '/vendor/application'
      preLoaderRoute: typeof VendorApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/customers': {
      id: '/vendor/customers'
      path: '/vendor/customers'
      fullPath: '/vendor/customers'
      preLoaderRoute: typeof VendorCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/notifications': {
      id: '/vendor/notifications'
      path: '/vendor/notifications'
      fullPath: '/vendor/notifications'
      preLoaderRoute: typeof VendorNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/vendor/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/payment-details': {
      id: '/vendor/payment-details'
      path: '/vendor/payment-details'
      fullPath: '/vendor/payment-details'
      preLoaderRoute: typeof VendorPaymentDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/pickup': {
      id: '/vendor/pickup'
      path: '/vendor/pickup'
      fullPath: '/vendor/pickup'
      preLoaderRoute: typeof VendorPickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/profile': {
      id: '/vendor/profile'
      path: '/vendor/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof VendorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/receipts': {
      id: '/vendor/receipts'
      path: '/vendor/receipts'
      fullPath: '/vendor/receipts'
      preLoaderRoute: typeof VendorReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/sales': {
      id: '/vendor/sales'
      path: '/vendor/sales'
      fullPath: '/vendor/sales'
      preLoaderRoute: typeof VendorSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/settings': {
      id: '/vendor/settings'
      path: '/vendor/settings'
      fullPath: '/vendor/settings'
      preLoaderRoute: typeof VendorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/shop': {
      id: '/vendor/shop'
      path: '/vendor/shop'
      fullPath: '/vendor/shop'
      preLoaderRoute: typeof VendorShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/subscription': {
      id: '/vendor/subscription'
      path: '/vendor/subscription'
      fullPath: '/vendor/subscription'
      preLoaderRoute: typeof VendorSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/support': {
      id: '/vendor/support'
      path: '/vendor/support'
      fullPath: '/vendor/support'
      preLoaderRoute: typeof VendorSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/config': {
      id: '/api/auth/config'
      path: '/api/auth/config'
      fullPath: '/api/auth/config'
      preLoaderRoute: typeof ApiAuthConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/webhook': {
      id: '/api/payments/webhook'
      path: '/api/payments/webhook'
      fullPath: '/api/payments/webhook'
      preLoaderRoute: typeof ApiPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/inventory/': {
      id: '/vendor/inventory/'
      path: '/vendor/inventory'
      fullPath: '/vendor/inventory/'
      preLoaderRoute: typeof VendorInventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/inventory/add': {
      id: '/vendor/inventory/add'
      path: '/vendor/inventory/add'
      fullPath: '/vendor/inventory/add'
      preLoaderRoute: typeof VendorInventoryAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/inventory/history': {
      id: '/vendor/inventory/history'
      path: '/vendor/inventory/history'
      fullPath: '/vendor/inventory/history'
      preLoaderRoute: typeof VendorInventoryHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/inventory/low-stock': {
      id: '/vendor/inventory/low-stock'
      path: '/vendor/inventory/low-stock'
      fullPath: '/vendor/inventory/low-stock'
      preLoaderRoute: typeof VendorInventoryLowStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/inventory/stock': {
      id: '/vendor/inventory/stock'
      path: '/vendor/inventory/stock'
      fullPath: '/vendor/inventory/stock'
      preLoaderRoute: typeof VendorInventoryStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/receipts/subscriptions': {
      id: '/vendor/receipts/subscriptions'
      path: '/subscriptions'
      fullPath: '/vendor/receipts/subscriptions'
      preLoaderRoute: typeof VendorReceiptsSubscriptionsRouteImport
      parentRoute: typeof VendorReceiptsRoute
    }
    '/vendor/subscription/payment-history': {
      id: '/vendor/subscription/payment-history'
      path: '/payment-history'
      fullPath: '/vendor/subscription/payment-history'
      preLoaderRoute: typeof VendorSubscriptionPaymentHistoryRouteImport
      parentRoute: typeof VendorSubscriptionRoute
    }
    '/vendor/subscription/plans': {
      id: '/vendor/subscription/plans'
      path: '/plans'
      fullPath: '/vendor/subscription/plans'
      preLoaderRoute: typeof VendorSubscriptionPlansRouteImport
      parentRoute: typeof VendorSubscriptionRoute
    }
    '/api/invoices/$orderId/pdf': {
      id: '/api/invoices/$orderId/pdf'
      path: '/api/invoices/$orderId/pdf'
      fullPath: '/api/invoices/$orderId/pdf'
      preLoaderRoute: typeof ApiInvoicesOrderIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface ProductsRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface VendorReceiptsRouteChildren {
  VendorReceiptsSubscriptionsRoute: typeof VendorReceiptsSubscriptionsRoute
}

const VendorReceiptsRouteChildren: VendorReceiptsRouteChildren = {
  VendorReceiptsSubscriptionsRoute: VendorReceiptsSubscriptionsRoute,
}

const VendorReceiptsRouteWithChildren = VendorReceiptsRoute._addFileChildren(
  VendorReceiptsRouteChildren,
)

interface VendorSubscriptionRouteChildren {
  VendorSubscriptionPaymentHistoryRoute: typeof VendorSubscriptionPaymentHistoryRoute
  VendorSubscriptionPlansRoute: typeof VendorSubscriptionPlansRoute
}

const VendorSubscriptionRouteChildren: VendorSubscriptionRouteChildren = {
  VendorSubscriptionPaymentHistoryRoute: VendorSubscriptionPaymentHistoryRoute,
  VendorSubscriptionPlansRoute: VendorSubscriptionPlansRoute,
}

const VendorSubscriptionRouteWithChildren =
  VendorSubscriptionRoute._addFileChildren(VendorSubscriptionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDeliveryPartnersRoute: AdminDeliveryPartnersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRefundsRoute: AdminRefundsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminShopsRoute: AdminShopsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  DeliveryAdminRoute: DeliveryAdminRoute,
  DeliveryDashboardRoute: DeliveryDashboardRoute,
  DeliveryEarningsRoute: DeliveryEarningsRoute,
  DeliveryHistoryRoute: DeliveryHistoryRoute,
  DeliveryNotificationsRoute: DeliveryNotificationsRoute,
  DeliveryOrdersRoute: DeliveryOrdersRoute,
  DeliveryProfileRoute: DeliveryProfileRoute,
  DeliveryRequestRoute: DeliveryRequestRoute,
  DeliverySettingsRoute: DeliverySettingsRoute,
  InvoiceOrderIdRoute: InvoiceOrderIdRoute,
  OrderSuccessOrderIdRoute: OrderSuccessOrderIdRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  VendorAdminRoute: VendorAdminRoute,
  VendorApplicationRoute: VendorApplicationRoute,
  VendorCustomersRoute: VendorCustomersRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  VendorNotificationsRoute: VendorNotificationsRoute,
  VendorOrdersRoute: VendorOrdersRoute,
  VendorPaymentDetailsRoute: VendorPaymentDetailsRoute,
  VendorPickupRoute: VendorPickupRoute,
  VendorProfileRoute: VendorProfileRoute,
  VendorReceiptsRoute: VendorReceiptsRouteWithChildren,
  VendorSalesRoute: VendorSalesRoute,
  VendorSettingsRoute: VendorSettingsRoute,
  VendorShopRoute: VendorShopRoute,
  VendorSubscriptionRoute: VendorSubscriptionRouteWithChildren,
  VendorSupportRoute: VendorSupportRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthConfigRoute: ApiAuthConfigRoute,
  ApiPaymentsWebhookRoute: ApiPaymentsWebhookRoute,
  VendorInventoryAddRoute: VendorInventoryAddRoute,
  VendorInventoryHistoryRoute: VendorInventoryHistoryRoute,
  VendorInventoryLowStockRoute: VendorInventoryLowStockRoute,
  VendorInventoryStockRoute: VendorInventoryStockRoute,
  VendorInventoryIndexRoute: VendorInventoryIndexRoute,
  ApiInvoicesOrderIdPdfRoute: ApiInvoicesOrderIdPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
